# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuitube < Formula
  desc "Terminal music player for curated YouTube channels with Claude MCP support"
  homepage "https://github.com/gitcoder89431/tuitube"
  version "0.2.0"
  license "MIT"

  depends_on "mpv"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitcoder89431/tuitube/releases/download/v0.2.0/tuitube_0.2.0_darwin_amd64.tar.gz"
      sha256 "14d8db73412e13aaf0eaad34898b690bdf619196fd1b264c39d4eae671fe93be"

      define_method(:install) do
        bin.install "tuitube"
        (share/"tuitube").install "catalog.db"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitcoder89431/tuitube/releases/download/v0.2.0/tuitube_0.2.0_darwin_arm64.tar.gz"
      sha256 "6b34dea35affdcad2362b4d80b50ff12f6ba18c478ac4039b726b8e73026eefe"

      define_method(:install) do
        bin.install "tuitube"
        (share/"tuitube").install "catalog.db"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcoder89431/tuitube/releases/download/v0.2.0/tuitube_0.2.0_linux_amd64.tar.gz"
      sha256 "fe698ffe2c263e8cd618a2ce290130d513fad73ba231c5dded7ee5a74dbbaa3c"
      define_method(:install) do
        bin.install "tuitube"
        (share/"tuitube").install "catalog.db"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcoder89431/tuitube/releases/download/v0.2.0/tuitube_0.2.0_linux_arm64.tar.gz"
      sha256 "f1f1092a4a29a5c4a7985659d7afc342520e8f2727ec7ac98ce78afa51dfe99f"
      define_method(:install) do
        bin.install "tuitube"
        (share/"tuitube").install "catalog.db"
      end
    end
  end

  test do
    system "#{bin}/tuitube", "--version"
  end
end
